name: flutter_cropper
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.2.0
  flutter_image_compress: ^2.3.0
  http: ^1.2.1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
